Correct typos in the appendix.
spring-cloud/spring-cloud-commons pull request #1149
Opened 2022-09-21 16:12 UTC by yoosh66

I found a typo in the appendix and corrected it.

2022-09-21 16:55 UTC, spencergibb requested changes

2022-09-21 17:45 UTC, yoosh66 commented on docs/src/main/asciidoc/_configprops.adoc
> +|spring.cloud.loadbalancer.retry.max-retries-on-same-service-instance | `+++0+++` | Number of retries to be executed on the same `ServiceInstance`.
I have edited the file you mentioned. thank you.

2023-01-17 12:40 UTC, OlgaMaciaszek approved these changes
Thanks @yoosh66. LGTM.

2023-01-17 12:48 UTC, OlgaMaciaszek commented
Merged via: fc445271d83ed55d41ff4c44b37b6cfbeb068eea.

2023-01-17 12:48 UTC, closed without merging