Lazy fills service instances to reduce max latency
spring-cloud/spring-cloud-commons pull request #1165
Opened 2022-10-30 16:57 UTC by jizhuozhi

When we have a lot of upstream services, and their total weight is large, then if we expand all instances in one request, our processing time will be very long. To solve this problem, use a lazily computed list to expand all elements to an unexpanded position only when the unexpanded position is visited.

There is an extreme case here. When using `RandomLoadBalancer`, it is possible to select a very late node for the first time, so the delay will still be large. But when we use `RoundRobinLoadBalancer`, we only move the position of one element at a time, so the effect is negligible.

2022-10-31 14:43 UTC, jizhuozhi commented
Hello, @OlgaMaciaszek . I create a PR that lazy fills service instances to reduce max latency, PLAT.

2022-11-02 11:48 UTC, OlgaMaciaszek requested changes
Thanks @jizhuozhi. Looks like a nice performance improving refactoring of the previous PR. The logic looks good, however I've added some comment regarding the code style and naming - please address.

2022-11-02 11:48 UTC, OlgaMaciaszek commented on spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/LazyWeightedServiceInstanceList.java
> +		int gcd = 0;
Please rename variable to `greatestCommonDivisor`.

2022-11-02 14:21 UTC, OlgaMaciaszek approved these changes
LGTM.

2022-11-02 14:21 UTC, merged