Refactor code to simplify calculation logic
spring-cloud/spring-cloud-commons pull request #1199
Opened 2023-01-19 06:54 UTC by jizhuozhi

The implemented logic is the same as #1184, both are O(1) schedulers, but the code implementation is simplified through double queues, and recursive processing that may cause errors is avoided

2023-02-01 12:39 UTC, OlgaMaciaszek reviewed
Thanks for the PR, @jizhuozhi - this in fact is simpler and more readable. Have added just one cosmetic comment - please address it.

2023-02-01 12:39 UTC, OlgaMaciaszek commented on spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/LazyWeightedServiceInstanceList.java
> +	static class O1ServiceInstanceSelector {
Maybe rename to sth like `WeightedInstanceSelector` as this puts focus on the main feature.

2023-02-01 12:40 UTC, OlgaMaciaszek requested changes
Thanks for the PR, @jizhuozhi - this in fact is simpler and more readable. Have added just one cosmetic comment - please address it.

2023-02-01 13:47 UTC, jizhuozhi commented
Hello, @OlgaMaciaszek . All conversation has resolved, PLAT :)

2023-02-02 11:41 UTC, OlgaMaciaszek approved these changes
Thanks, @jizhuozhi. LGTM.

2023-02-02 11:41 UTC, merged