added probe implementation to CompositeDiscoveryClient
spring-cloud/spring-cloud-commons pull request #1210
Opened 2023-03-01 19:59 UTC by sruffatti

Fixes gh-1209

2023-03-01 20:56 UTC, spencergibb requested changes
Please add a test

2023-03-06 19:20 UTC, sruffatti commented
Any additional feedback on this @spencergibb ?

2023-04-05 21:17 UTC, sruffatti commented
Any updates on this @spencergibb ?

2023-05-10 19:54 UTC, sruffatti commented
bump @spencergibb

2023-05-30 22:33 UTC, sruffatti commented
@OlgaMaciaszek Are you able to help me out here? This PR has been open for a while.

2023-05-31 17:08 UTC, OlgaMaciaszek requested changes
Hi @sruffatti, thanks for submitting the PR. Makes sense. There are some minor style issues. I have added comments - please address them. Also, could you please file this against `3.1.x` instead of `main`? It'll be considered a bugfix, so we'd like for it to also be included in the `2021.0.x` release train.

2023-05-31 17:08 UTC, OlgaMaciaszek commented on spring-cloud-commons/src/test/java/org/springframework/cloud/client/discovery/composite/CompositeDiscoveryClientUnitTests.java
> +     void getDescriptionShouldBeComposite() {
Please remove this test - we don't really need to test hard-coded `String` values.

2023-05-31 17:08 UTC, OlgaMaciaszek commented on spring-cloud-commons/src/test/java/org/springframework/cloud/client/discovery/composite/CompositeDiscoveryClientUnitTests.java
> +     void getInstancesByServiceIdShouldReturnServiceInstances() {
Please rename the test to `shouldRetrieveInstancesByServiceId`.

2023-05-31 17:08 UTC, OlgaMaciaszek commented on spring-cloud-commons/src/test/java/org/springframework/cloud/client/discovery/composite/CompositeDiscoveryClientUnitTests.java
> +     void getServicesShouldReturnServiceIds() {
Please rename the test to `shouldReturnServiceIds`.

2023-05-31 17:08 UTC, OlgaMaciaszek commented on spring-cloud-commons/src/test/java/org/springframework/cloud/client/discovery/composite/CompositeDiscoveryClientUnitTests.java
> +     void getDiscoveryClientsShouldReturnAllDiscoveryClients() {
Please rename the test to `shouldReturnAllDiscoveryClients`.

2023-05-31 17:08 UTC, OlgaMaciaszek commented on spring-cloud-commons/src/test/java/org/springframework/cloud/client/discovery/composite/CompositeDiscoveryClientUnitTests.java
> +     void probeShouldCallProbeInAllClientBeans() {
Please rename to `shouldCallProbeOnAllDiscoveryClients`.

2023-05-31 17:08 UTC, OlgaMaciaszek commented on spring-cloud-commons/src/test/java/org/springframework/cloud/client/discovery/composite/CompositeDiscoveryClientUnitTests.java
> + * Copyright 2012-2020 the original author or authors.
Please update the copyright dates to `2012-2023`.

2023-05-31 17:08 UTC, OlgaMaciaszek commented on spring-cloud-commons/src/main/java/org/springframework/cloud/client/discovery/composite/CompositeDiscoveryClient.java
> +	@Override
Please add your name with `@author` tag in the javadoc of the edited file. Please update the copyright date line.

2023-05-31 18:13 UTC, sruffatti commented
> Hi @sruffatti, thanks for submitting the PR. Makes sense. There are some minor style issues. I have added comments - please address them. Also, could you please file this against `3.1.x` instead of `main`? It'll be considered a bugfix, so we'd like for it to also be included in the `2021.0.x` release train.

@OlgaMaciaszek I addressed your comments. Are you asking me to change the target branch to `3.1.x` instead `main`? When I do that I see more commits. Are you asking me to branch off `3.1.x`, add my changes, and then open a PR?

2023-06-01 11:01 UTC, OlgaMaciaszek commented
Hi @sruffatti,
> @OlgaMaciaszek I addressed your comments. Are you asking me to change the target branch to 3.1.x instead main? When I do that I see many commits included in the PR. Are you asking me to branch off 3.1.x, add my changes, and then open a PR? 

The second approach will probably be faster and easier, so it's a good idea.

2023-06-01 17:55 UTC, sruffatti commented
@OlgaMaciaszek I created another PR merging to 3.1.x here https://github.com/spring-cloud/spring-cloud-commons/pull/1239

2023-06-02 11:19 UTC, OlgaMaciaszek commented
Closing in favour of https://github.com/spring-cloud/spring-cloud-commons/pull/1239.

2023-06-02 11:19 UTC, closed without merging