replace poor punctuation and naming
spring-cloud/spring-cloud-commons pull request #1236
Opened 2023-05-17 06:28 UTC by GierSmith

The name of the variable is o_O does not conform to Java's naming rules. 
"..." uses the wrong punctuation

2023-05-17 06:28 UTC, pivotal-cla commented
@GierSmith Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-commons&pullRequestId=1236)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-commons&pullRequestId=1236) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2023-05-17 06:36 UTC, pivotal-cla commented
@GierSmith Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-commons&pullRequestId=1236)!

2023-06-01 11:12 UTC, OlgaMaciaszek requested changes
Hello @GierSmith, thanks for submitting a PR. `...` has correct punctuation - you do not put spaces in between. Please revert that change. I agree the exception name could be improved, but we try to avoid non-explicit, single-letter variable names in favour of more meaningful naming. Please rename `e` to `exception`. Also, please remember to update copyright dates (above) to `-2023` in any changed java files.

2023-06-01 13:07 UTC, GierSmith commented
The `...` in the previous version was not an English character, my commit changed it to an English character, I think this is the correct change.

2023-11-13 13:05 UTC, OlgaMaciaszek commented
@Buzzardo - could you please take a look?

2023-11-13 16:21 UTC, Buzzardo approved these changes

2023-11-13 17:08 UTC, merged