Fix #1285 Spring Cloud activates unexpected profiles when some conditions met
spring-cloud/spring-cloud-commons pull request #1286
Opened 2023-09-29 06:56 UTC by leovx

https://github.com/spring-cloud/spring-cloud-commons/issues/1285

2023-10-11 10:06 UTC, yanhom1314 commented
I recently upgraded to version 3.1.4 and encountered an issue with retrieving active profiles from different PropertySources.

2023-10-11 10:37 UTC, leovx commented
> I recently upgraded to version 3.1.4 and encountered an issue with retrieving profiles from different PropertySources. I want to know if this is considered a bug, as previous versions did not have this problem.

Not quite aware of your problem, coz I only found this issue comparing 3.1.7 and 3.1.6. You can check if your issue persists in the latest version and possibly provide a POC.

2023-10-17 14:08 UTC, ryanjbaxter requested changes
You will need to change the PR to be against the 3.1.x branch and also fix the checkstyle errors.

2023-10-18 14:03 UTC, leovx commented
> You will need to change the PR to be against the 3.1.x branch and also fix the checkstyle errors.

Code style issues fixed and rebased to 3.1.x.

2023-10-18 21:04 UTC, merged