@LoadBalanced RestClient
spring-cloud/spring-cloud-commons pull request #1294
Opened 2023-11-09 17:06 UTC by OlgaMaciaszek

Fixes gh-1293.

2023-11-10 13:01 UTC, OlgaMaciaszek commented
Hi @Buzzardo, could you please review documentation changes?

2023-11-13 14:21 UTC, ryanjbaxter approved these changes

2023-11-13 16:38 UTC, Buzzardo requested changes
Good changes. Sorry about the code font not rendering in headings. Your instinct to put it in is correct, but it doesn't work well across our various outputs.

2023-11-13 16:38 UTC, Buzzardo commented on docs/modules/ROOT/pages/spring-cloud-commons/common-abstractions.adoc
> +== Spring `RestTemplate` as a LoadBalancer Client
Remove the ticks around `RestTemplate`. Your instinct is right, but we have had trouble with rendering code fonts in headings, so we had to remove it.

2023-11-13 16:38 UTC, Buzzardo commented on docs/modules/ROOT/pages/spring-cloud-commons/common-abstractions.adoc
> +=== Multiple `RestTemplate` Objects
Remove the ticks around `RestTemplate`. As I mentioned in the previous comment, we have trouble with rendering the code font in headings.

2023-11-13 16:38 UTC, Buzzardo commented on docs/modules/ROOT/pages/spring-cloud-commons/common-abstractions.adoc
> +== Spring `RestClient` as a LoadBalancer Client
Remove the ticks around `RestClient`. It won't render correctly.

2023-11-13 16:38 UTC, Buzzardo commented on docs/modules/ROOT/pages/spring-cloud-commons/common-abstractions.adoc
> +Add xref:spring-cloud-commons/loadbalancer.adoc#spring-cloud-loadbalancer-starter[Spring Cloud LoadBalancer starter] to your project in order to use it.
Change to:

To use it, add xref:spring-cloud-commons/loadbalancer.adoc#spring-cloud-loadbalancer-starter[Spring Cloud LoadBalancer starter] to your project.

2023-11-13 16:38 UTC, Buzzardo commented on docs/modules/ROOT/pages/spring-cloud-commons/common-abstractions.adoc
> +== Spring `WebClient` as a LoadBalancer Client
Remove the ticks around `WebClient`. The code font does not render correctly in headings.

2023-11-13 16:38 UTC, Buzzardo commented on docs/modules/ROOT/pages/spring-cloud-commons/common-abstractions.adoc
> +=== Multiple `WebClient.Builder` Objects
Remove the ticks around `WebClient.Builder`. The code font does not render correctly in headings.

2023-11-13 16:38 UTC, Buzzardo commented on docs/modules/ROOT/pages/spring-cloud-commons/loadbalancer.adoc
> +In order to make it easy to use Spring Cloud LoadBalancer, we provide `ReactorLoadBalancerExchangeFilterFunction` that can be used with `WebClient` and `BlockingLoadBalancerClient` that works with `R
Change to:

To make it easy to use Spring Cloud LoadBalancer, we provide `ReactorLoadBalancerExchangeFilterFunction` (which can be used with `WebClient`) and `BlockingLoadBalancerClient` (which works with `RestTemplate` and `RestClient`).

--------

The parentheses break up a long sentence and make it more clear. "In order to" can nearly always be changed to "To". Edit to add: That's not your fault. That sentence had problems in the first place. While we have the chance, though, we may as well improve it.

2023-11-13 16:38 UTC, Buzzardo commented on docs/modules/ROOT/pages/spring-cloud-commons/loadbalancer.adoc
> +You can also pass your own `WebClient`, `RestTemplate` or `RestClient` instance to be used for the checks.
Add a comma after `RestTemplate. The Spring Style Guide calls for serial commas (a comma before the last item in a list).

2023-11-13 17:06 UTC, OlgaMaciaszek commented
Thanks, @Buzzardo 🙂

2023-11-13 17:12 UTC, merged