Add retry support for blocking LoadBalancer
spring-cloud/spring-cloud-commons pull request #832
Opened 2020-09-23 17:24 UTC by OlgaMaciaszek

Fixes gh-829

2020-09-23 19:47 UTC, Buzzardo requested changes

2020-09-23 19:47 UTC, Buzzardo commented on docs/src/main/asciidoc/spring-cloud-commons.adoc
> +You can use `client.ribbon.MaxAutoRetries`, `client.ribbon.MaxAutoRetriesNextServer`, and `client.ribbon.OkToRetryOnAllOperations` properties.
Add "the" after "use"

2020-09-23 19:47 UTC, Buzzardo commented on docs/src/main/asciidoc/spring-cloud-commons.adoc
> +- `spring.cloud.loadbalancer.retry.maxRetriesOnSameServiceInstance` - indicates how many times a request should be retried on the same ServiceInstance (counted separately for every selected instance)
Make "ServiceInstance" be code (add backticks around it.

2020-09-23 19:47 UTC, Buzzardo commented on docs/src/main/asciidoc/spring-cloud-commons.adoc
> +- `spring.cloud.loadbalancer.retry.maxRetriesOnNextServiceInstance` - indicates how many times a request should be retried a newly selected ServiceInstance
Make "ServiceInstance" be code (add backticks around it.

2020-09-24 14:40 UTC, spencergibb commented on spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/blocking/retry/BlockingLoadBalancedRetryPolicy.java
> +	private final ServiceInstanceChooser loadBalancerClient;
field name? `serviceInstanceChooser`

2020-09-24 14:55 UTC, spencergibb approved these changes

2020-09-24 15:31 UTC, merged