Code changes for Issue 824 (https://github.com/spring-cloud/spring-cloud-commons/issues/824)
spring-cloud/spring-cloud-commons pull request #835
Opened 2020-10-01 23:47 UTC by alchemy24

Please review the code changes for the Issue 824 (https://github.com/spring-cloud/spring-cloud-commons/issues/824)

Unit Tests passed locally via mvn install -P spring

2020-10-01 23:47 UTC, pivotal-issuemaster commented
@alchemy24 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-commons&pullRequestId=835)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-commons&pullRequestId=835) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2020-10-01 23:47 UTC, OlgaMaciaszek commented
Fixes gh-824.

2020-10-01 23:49 UTC, pivotal-issuemaster commented
@alchemy24 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-commons&pullRequestId=835)!

2020-10-06 15:03 UTC, OlgaMaciaszek requested changes
@alchemy24 Thanks for submitting the PR. I've added some comments for you to address. Also, please add your name to class authors with `@author` tag to all the classes that you've modified.

2020-10-06 15:03 UTC, OlgaMaciaszek commented
Fixes gh-824.

2020-10-07 03:41 UTC, alchemy24 commented on spring-cloud-commons/src/test/java/org/springframework/cloud/client/loadbalancer/reactive/ReactorLoadBalancerExchangeFilterFunctionTests.java
> +		DefaultServiceInstance instance = new DefaultServiceInstance(null, null, null, 0,
Sure. I will make the change

2020-10-07 03:42 UTC, alchemy24 commented on spring-cloud-commons/src/test/java/org/springframework/cloud/client/loadbalancer/reactive/LoadBalancerExchangeFilterFunctionTests.java
> +		DefaultServiceInstance instance = new DefaultServiceInstance(null, null, null, 0,
Sure. I will make the change

2020-10-07 03:42 UTC, alchemy24 commented on spring-cloud-commons/src/main/java/org/springframework/cloud/client/DefaultServiceInstance.java
> +	private boolean secure = false;
Sounds good

2020-10-07 03:42 UTC, alchemy24 commented on spring-cloud-commons/src/main/java/org/springframework/cloud/client/discovery/simple/reactive/SimpleReactiveDiscoveryProperties.java
> +	private DefaultServiceInstance local = new DefaultServiceInstance(null, null, null, 0,
Sure. Will make the change

2020-10-07 03:42 UTC, alchemy24 commented on spring-cloud-commons/src/main/java/org/springframework/cloud/client/discovery/simple/SimpleDiscoveryProperties.java
>  	 */
Sounds good. Will make the change

2020-10-07 05:37 UTC, alchemy24 commented
@OlgaMaciaszek Have fixed all the review comments. Let me know if it looks good

2020-10-12 11:41 UTC, OlgaMaciaszek approved these changes

2020-10-12 11:41 UTC, merged