Fixes gh-898
spring-cloud/spring-cloud-commons pull request #907
Opened 2021-02-18 08:58 UTC by ovgusev

If HikariDataSource bean gets AOP-proxied more than once, the spring-cloud rebind operation doesn't treat it as never-refreshable.

2021-02-18 08:58 UTC, pivotal-issuemaster commented
@ovgusev Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-commons&pullRequestId=907)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-commons&pullRequestId=907) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2021-02-18 08:58 UTC, pivotal-issuemaster commented
@ovgusev Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-commons&pullRequestId=907)!

2021-07-01 19:34 UTC, ryanjbaxter requested changes
I don't see a need for a new method, I think we can change the behavior of the original method

2021-07-05 14:44 UTC, OlgaMaciaszek commented
@ovgusev, thanks for submitting this PR. Since this code is also being used in the `Hoxton` release train, I'm going to cherry-pick your commit directly to `2.2.x` to get it out in the upcoming `Hoxton` release, and also move the changes under the existing method signature as @ryanjbaxter has suggested.

2021-07-05 14:44 UTC, OlgaMaciaszek commented
Closing with b628338e54f638aee1913956c154a73a435e52df.

2021-07-05 14:44 UTC, closed without merging