Implemented clients eager load
spring-cloud/spring-cloud-commons pull request #929
Opened 2021-03-17 12:41 UTC by Ferioney

Fixes gh-729

2021-06-03 17:31 UTC, spencergibb requested changes

2021-06-03 17:31 UTC, spencergibb commented on spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/support/LoadBalancerEagerContextInitializer.java
> +	private void warnUpFunction() {
no need for a separate method

2021-06-03 17:31 UTC, spencergibb commented on spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/config/LoadBalancerAutoConfiguration.java
> +	@ConditionalOnProperty(value = "spring.cloud.loadbalancer.eager-load.enabled", havingValue = "true")
Should activation be if clients is not empty? Why set two properties?

2021-06-10 13:08 UTC, OlgaMaciaszek requested changes
@Ferioney thanks for submitting the PR. Other than some minor changes described in the comments, it looks good. Please also add a documentation subsection in `spring-cloud-commons.adoc` within the "Spring Cloud LoadBalancer" section.

2021-06-10 13:08 UTC, OlgaMaciaszek commented on spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/support/LoadBalancerEagerContextInitializer.java
> +		this.serviceNames.forEach(factory::getInstance);
Please remove unnecessary `this.` keyword.

2021-06-10 13:08 UTC, OlgaMaciaszek commented
@Ferioney Please also resolve conflicts.

2022-06-24 11:11 UTC, dplesa commented
@OlgaMaciaszek or @Ferioney, can you please finish the work on this issue and merge it, since this feature is really important.

2022-07-01 16:17 UTC, OlgaMaciaszek commented
Merged within d84c772b7e6ba9b5841449aad08384973c591ce5. Thanks again for submitting it @Ferioney .

2022-07-01 16:17 UTC, closed without merging